/** This file is auto-generated by build-openapi-client.mts. Do not edit directly. */import pathUnix from "node:path/posix"
import type * as openapi from "./schemas.ts";


export type GetPersonalizedForYouFeedQueryParams = {
  limit: number;
  cursor: string;
}

export type GetPersonalizedForYouFeedResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetPersonalizedForYouFeedResponse401 = openapi.Error

export type GetPersonalizedForYouFeedResponse403 = openapi.Error

export type GetPersonalizedForYouFeedResponse429 = openapi.RateLimitError

export type GetPersonalizedForYouFeedResponse = [[200, GetPersonalizedForYouFeedResponse200], [401, GetPersonalizedForYouFeedResponse401], [403, GetPersonalizedForYouFeedResponse403], [429, GetPersonalizedForYouFeedResponse429]]

export interface GetPersonalizedForYouFeedAPI {
  id: "GetPersonalizedForYouFeed";
  method: "get";
  query: GetPersonalizedForYouFeedQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetPersonalizedForYouFeedResponse;
}

export type GetFeedWithTrendingAndPopularPostsQueryParams = {
  limit: number;
  cursor: string;
  tags: string;
}

export type GetFeedWithTrendingAndPopularPostsResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetFeedWithTrendingAndPopularPostsResponse401 = openapi.Error

export type GetFeedWithTrendingAndPopularPostsResponse429 = openapi.RateLimitError

export type GetFeedWithTrendingAndPopularPostsResponse = [[200, GetFeedWithTrendingAndPopularPostsResponse200], [401, GetFeedWithTrendingAndPopularPostsResponse401], [429, GetFeedWithTrendingAndPopularPostsResponse429]]

export interface GetFeedWithTrendingAndPopularPostsAPI {
  id: "GetFeedWithTrendingAndPopularPosts";
  method: "get";
  query: GetFeedWithTrendingAndPopularPostsQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetFeedWithTrendingAndPopularPostsResponse;
}

export type GetFeedOfPostsWithDiscussionsQueryParams = {
  limit: number;
  cursor: string;
  period: number;
  tag: string;
  source: string;
}

export type GetFeedOfPostsWithDiscussionsResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetFeedOfPostsWithDiscussionsResponse401 = openapi.Error

export type GetFeedOfPostsWithDiscussionsResponse429 = openapi.RateLimitError

export type GetFeedOfPostsWithDiscussionsResponse = [[200, GetFeedOfPostsWithDiscussionsResponse200], [401, GetFeedOfPostsWithDiscussionsResponse401], [429, GetFeedOfPostsWithDiscussionsResponse429]]

export interface GetFeedOfPostsWithDiscussionsAPI {
  id: "GetFeedOfPostsWithDiscussions";
  method: "get";
  query: GetFeedOfPostsWithDiscussionsQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetFeedOfPostsWithDiscussionsResponse;
}

export type GetPostsByTagQueryParams = {
  limit: number;
  cursor: string;
}

export type GetPostsByTagPathParams = {
  tag: string;
}

export type GetPostsByTagResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetPostsByTagResponse401 = openapi.Error

export type GetPostsByTagResponse429 = openapi.RateLimitError

export type GetPostsByTagResponse = [[200, GetPostsByTagResponse200], [401, GetPostsByTagResponse401], [429, GetPostsByTagResponse429]]

export interface GetPostsByTagAPI {
  id: "GetPostsByTag";
  method: "get";
  query: GetPostsByTagQueryParams;
  pathParams: GetPostsByTagPathParams;
  requestBody: null;
  response: GetPostsByTagResponse;
}

export type GetPostsBySourceQueryParams = {
  limit: number;
  cursor: string;
}

export type GetPostsBySourcePathParams = {
  source: string;
}

export type GetPostsBySourceResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetPostsBySourceResponse401 = openapi.Error

export type GetPostsBySourceResponse429 = openapi.RateLimitError

export type GetPostsBySourceResponse = [[200, GetPostsBySourceResponse200], [401, GetPostsBySourceResponse401], [429, GetPostsBySourceResponse429]]

export interface GetPostsBySourceAPI {
  id: "GetPostsBySource";
  method: "get";
  query: GetPostsBySourceQueryParams;
  pathParams: GetPostsBySourcePathParams;
  requestBody: null;
  response: GetPostsBySourceResponse;
}

export type GetPostDetailsByIDPathParams = {
  id: string;
}

export type GetPostDetailsByIDResponse200 = {
  data: openapi.PostDetail;
}

export type GetPostDetailsByIDResponse401 = openapi.Error

export type GetPostDetailsByIDResponse403 = openapi.Error

export type GetPostDetailsByIDResponse404 = openapi.Error

export type GetPostDetailsByIDResponse = [[200, GetPostDetailsByIDResponse200], [401, GetPostDetailsByIDResponse401], [403, GetPostDetailsByIDResponse403], [404, GetPostDetailsByIDResponse404]]

export interface GetPostDetailsByIDAPI {
  id: "GetPostDetailsByID";
  method: "get";
  query: null;
  pathParams: GetPostDetailsByIDPathParams;
  requestBody: null;
  response: GetPostDetailsByIDResponse;
}

export type GetCommentsForAPostQueryParams = {
  limit: number;
  cursor: string;
  sort: string;
}

export type GetCommentsForAPostPathParams = {
  id: string;
}

export type GetCommentsForAPostResponse200 = {
  data: Array<openapi.Comment>;
  pagination: openapi.Pagination;
}

export type GetCommentsForAPostResponse401 = openapi.Error

export type GetCommentsForAPostResponse404 = openapi.Error

export type GetCommentsForAPostResponse429 = openapi.RateLimitError

export type GetCommentsForAPostResponse = [[200, GetCommentsForAPostResponse200], [401, GetCommentsForAPostResponse401], [404, GetCommentsForAPostResponse404], [429, GetCommentsForAPostResponse429]]

export interface GetCommentsForAPostAPI {
  id: "GetCommentsForAPost";
  method: "get";
  query: GetCommentsForAPostQueryParams;
  pathParams: GetCommentsForAPostPathParams;
  requestBody: null;
  response: GetCommentsForAPostResponse;
}

export type GetSearchPostsByKeywordQueryParams = {
  q: string;
  limit: number;
  cursor: string;
  time: string;
}

export type GetSearchPostsByKeywordResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetSearchPostsByKeywordResponse400 = openapi.Error

export type GetSearchPostsByKeywordResponse401 = openapi.Error

export type GetSearchPostsByKeywordResponse429 = openapi.RateLimitError

export type GetSearchPostsByKeywordResponse = [[200, GetSearchPostsByKeywordResponse200], [400, GetSearchPostsByKeywordResponse400], [401, GetSearchPostsByKeywordResponse401], [429, GetSearchPostsByKeywordResponse429]]

export interface GetSearchPostsByKeywordAPI {
  id: "GetSearchPostsByKeyword";
  method: "get";
  query: GetSearchPostsByKeywordQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetSearchPostsByKeywordResponse;
}

export type GetSearchTagsByNameQueryParams = {
  q: string;
}

export type GetSearchTagsByNameResponse200 = {
  data: Array<openapi.Tag>;
}

export type GetSearchTagsByNameResponse400 = openapi.Error

export type GetSearchTagsByNameResponse401 = openapi.Error

export type GetSearchTagsByNameResponse429 = openapi.RateLimitError

export type GetSearchTagsByNameResponse = [[200, GetSearchTagsByNameResponse200], [400, GetSearchTagsByNameResponse400], [401, GetSearchTagsByNameResponse401], [429, GetSearchTagsByNameResponse429]]

export interface GetSearchTagsByNameAPI {
  id: "GetSearchTagsByName";
  method: "get";
  query: GetSearchTagsByNameQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetSearchTagsByNameResponse;
}

export type GetSearchSourcesPublishersByNameQueryParams = {
  q: string;
  limit: number;
}

export type GetSearchSourcesPublishersByNameResponse200 = {
  data: Array<openapi.SourceSummary>;
}

export type GetSearchSourcesPublishersByNameResponse400 = openapi.Error

export type GetSearchSourcesPublishersByNameResponse401 = openapi.Error

export type GetSearchSourcesPublishersByNameResponse429 = openapi.RateLimitError

export type GetSearchSourcesPublishersByNameResponse = [[200, GetSearchSourcesPublishersByNameResponse200], [400, GetSearchSourcesPublishersByNameResponse400], [401, GetSearchSourcesPublishersByNameResponse401], [429, GetSearchSourcesPublishersByNameResponse429]]

export interface GetSearchSourcesPublishersByNameAPI {
  id: "GetSearchSourcesPublishersByName";
  method: "get";
  query: GetSearchSourcesPublishersByNameQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetSearchSourcesPublishersByNameResponse;
}

export type GetUserSBookmarkedPostsQueryParams = {
  limit: number;
  cursor: string;
  unreadOnly: boolean;
  listId: string;
}

export type GetUserSBookmarkedPostsResponse200 = {
  data: Array<openapi.BookmarkedPost>;
  pagination: openapi.Pagination;
}

export type GetUserSBookmarkedPostsResponse401 = openapi.Error

export type GetUserSBookmarkedPostsResponse429 = openapi.RateLimitError

export type GetUserSBookmarkedPostsResponse = [[200, GetUserSBookmarkedPostsResponse200], [401, GetUserSBookmarkedPostsResponse401], [429, GetUserSBookmarkedPostsResponse429]]

export interface GetUserSBookmarkedPostsAPI {
  id: "GetUserSBookmarkedPosts";
  method: "get";
  query: GetUserSBookmarkedPostsQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetUserSBookmarkedPostsResponse;
}

export type PostAddPostsToBookmarksRequestBody = {
  postIds: Array<string>;
  listId: string;
}

export type PostAddPostsToBookmarksResponse200 = {
  data: Array<{
      postId: string;
      createdAt: string;
      listId: string | null;
    }>;
}

export type PostAddPostsToBookmarksResponse400 = openapi.Error

export type PostAddPostsToBookmarksResponse401 = openapi.Error

export type PostAddPostsToBookmarksResponse429 = openapi.RateLimitError

export type PostAddPostsToBookmarksResponse = [[200, PostAddPostsToBookmarksResponse200], [400, PostAddPostsToBookmarksResponse400], [401, PostAddPostsToBookmarksResponse401], [429, PostAddPostsToBookmarksResponse429]]

export interface PostAddPostsToBookmarksAPI {
  id: "PostAddPostsToBookmarks";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostAddPostsToBookmarksRequestBody;
  response: PostAddPostsToBookmarksResponse;
}

export type GetSearchWithinBookmarksQueryParams = {
  q: string;
  limit: number;
  cursor: string;
  unreadOnly: boolean;
  listId: string;
}

export type GetSearchWithinBookmarksResponse200 = {
  data: Array<openapi.BookmarkedPost>;
  pagination: openapi.Pagination;
}

export type GetSearchWithinBookmarksResponse400 = openapi.Error

export type GetSearchWithinBookmarksResponse401 = openapi.Error

export type GetSearchWithinBookmarksResponse429 = openapi.RateLimitError

export type GetSearchWithinBookmarksResponse = [[200, GetSearchWithinBookmarksResponse200], [400, GetSearchWithinBookmarksResponse400], [401, GetSearchWithinBookmarksResponse401], [429, GetSearchWithinBookmarksResponse429]]

export interface GetSearchWithinBookmarksAPI {
  id: "GetSearchWithinBookmarks";
  method: "get";
  query: GetSearchWithinBookmarksQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetSearchWithinBookmarksResponse;
}

export type GetUserSBookmarkListsResponse200 = {
  data: Array<openapi.BookmarkList>;
}

export type GetUserSBookmarkListsResponse401 = openapi.Error

export type GetUserSBookmarkListsResponse429 = openapi.RateLimitError

export type GetUserSBookmarkListsResponse = [[200, GetUserSBookmarkListsResponse200], [401, GetUserSBookmarkListsResponse401], [429, GetUserSBookmarkListsResponse429]]

export interface GetUserSBookmarkListsAPI {
  id: "GetUserSBookmarkLists";
  method: "get";
  query: null;
  pathParams: null;
  requestBody: null;
  response: GetUserSBookmarkListsResponse;
}

export type PostCreateANewBookmarkListRequestBody = {
  name: string;
  icon: string;
}

export type PostCreateANewBookmarkListResponse200 = {
  data: openapi.BookmarkList;
}

export type PostCreateANewBookmarkListResponse400 = openapi.Error

export type PostCreateANewBookmarkListResponse401 = openapi.Error

export type PostCreateANewBookmarkListResponse429 = openapi.RateLimitError

export type PostCreateANewBookmarkListResponse = [[200, PostCreateANewBookmarkListResponse200], [400, PostCreateANewBookmarkListResponse400], [401, PostCreateANewBookmarkListResponse401], [429, PostCreateANewBookmarkListResponse429]]

export interface PostCreateANewBookmarkListAPI {
  id: "PostCreateANewBookmarkList";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostCreateANewBookmarkListRequestBody;
  response: PostCreateANewBookmarkListResponse;
}

export type DeleteABookmarkListPathParams = {
  id: string;
}

export type DeleteABookmarkListResponse401 = openapi.Error

export type DeleteABookmarkListResponse404 = openapi.Error

export type DeleteABookmarkListResponse429 = openapi.RateLimitError

export type DeleteABookmarkListResponse = [[401, DeleteABookmarkListResponse401], [404, DeleteABookmarkListResponse404], [429, DeleteABookmarkListResponse429]]

export interface DeleteABookmarkListAPI {
  id: "DeleteABookmarkList";
  method: "delete";
  query: null;
  pathParams: DeleteABookmarkListPathParams;
  requestBody: null;
  response: DeleteABookmarkListResponse;
}

export type DeleteRemoveAPostFromBookmarksPathParams = {
  id: string;
}

export type DeleteRemoveAPostFromBookmarksResponse401 = openapi.Error

export type DeleteRemoveAPostFromBookmarksResponse404 = openapi.Error

export type DeleteRemoveAPostFromBookmarksResponse429 = openapi.RateLimitError

export type DeleteRemoveAPostFromBookmarksResponse = [[401, DeleteRemoveAPostFromBookmarksResponse401], [404, DeleteRemoveAPostFromBookmarksResponse404], [429, DeleteRemoveAPostFromBookmarksResponse429]]

export interface DeleteRemoveAPostFromBookmarksAPI {
  id: "DeleteRemoveAPostFromBookmarks";
  method: "delete";
  query: null;
  pathParams: DeleteRemoveAPostFromBookmarksPathParams;
  requestBody: null;
  response: DeleteRemoveAPostFromBookmarksResponse;
}

export type PatchMoveABookmarkToAListOrRemoveFromListPathParams = {
  id: string;
}

export type PatchMoveABookmarkToAListOrRemoveFromListRequestBody = {
  listId: string | null;
}

export type PatchMoveABookmarkToAListOrRemoveFromListResponse401 = openapi.Error

export type PatchMoveABookmarkToAListOrRemoveFromListResponse403 = openapi.Error

export type PatchMoveABookmarkToAListOrRemoveFromListResponse404 = openapi.Error

export type PatchMoveABookmarkToAListOrRemoveFromListResponse429 = openapi.RateLimitError

export type PatchMoveABookmarkToAListOrRemoveFromListResponse = [[401, PatchMoveABookmarkToAListOrRemoveFromListResponse401], [403, PatchMoveABookmarkToAListOrRemoveFromListResponse403], [404, PatchMoveABookmarkToAListOrRemoveFromListResponse404], [429, PatchMoveABookmarkToAListOrRemoveFromListResponse429]]

export interface PatchMoveABookmarkToAListOrRemoveFromListAPI {
  id: "PatchMoveABookmarkToAListOrRemoveFromList";
  method: "patch";
  query: null;
  pathParams: PatchMoveABookmarkToAListOrRemoveFromListPathParams;
  requestBody: PatchMoveABookmarkToAListOrRemoveFromListRequestBody;
  response: PatchMoveABookmarkToAListOrRemoveFromListResponse;
}

export type GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse200 = {
  data: Array<{
      id: number;
      title: string;
      description: string;
      defaultEnabledState: boolean;
      group: string;
    }>;
}

export type GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse401 = openapi.Error

export type GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse429 = openapi.RateLimitError

export type GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse = [[200, GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse200], [401, GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse401], [429, GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse429]]

export interface GetAllAvailableAdvancedSettingsThatCanBeConfiguredForAPI {
  id: "GetAllAvailableAdvancedSettingsThatCanBeConfiguredFor";
  method: "get";
  query: null;
  pathParams: null;
  requestBody: null;
  response: GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse;
}

export type PostCreateANewCustomFeedRequestBody = {
  name: string;
  icon: string;
  orderBy: string;
  minDayRange: number;
  minUpvotes: number;
  minViews: number;
  disableEngagementFilter: boolean;
}

export type PostCreateANewCustomFeedResponse200 = openapi.CustomFeed

export type PostCreateANewCustomFeedResponse401 = openapi.Error

export type PostCreateANewCustomFeedResponse429 = openapi.RateLimitError

export type PostCreateANewCustomFeedResponse = [[200, PostCreateANewCustomFeedResponse200], [401, PostCreateANewCustomFeedResponse401], [429, PostCreateANewCustomFeedResponse429]]

export interface PostCreateANewCustomFeedAPI {
  id: "PostCreateANewCustomFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostCreateANewCustomFeedRequestBody;
  response: PostCreateANewCustomFeedResponse;
}

export type GetListUserSCustomFeedsQueryParams = {
  limit: number;
  cursor: string;
}

export type GetListUserSCustomFeedsResponse200 = {
  data: Array<openapi.CustomFeed>;
  pagination: openapi.Pagination;
}

export type GetListUserSCustomFeedsResponse401 = openapi.Error

export type GetListUserSCustomFeedsResponse429 = openapi.RateLimitError

export type GetListUserSCustomFeedsResponse = [[200, GetListUserSCustomFeedsResponse200], [401, GetListUserSCustomFeedsResponse401], [429, GetListUserSCustomFeedsResponse429]]

export interface GetListUserSCustomFeedsAPI {
  id: "GetListUserSCustomFeeds";
  method: "get";
  query: GetListUserSCustomFeedsQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetListUserSCustomFeedsResponse;
}

export type GetACustomFeedSPostsQueryParams = {
  limit: number;
  cursor: string;
}

export type GetACustomFeedSPostsPathParams = {
  feedId: string;
}

export type GetACustomFeedSPostsResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetACustomFeedSPostsResponse401 = openapi.Error

export type GetACustomFeedSPostsResponse404 = openapi.Error

export type GetACustomFeedSPostsResponse429 = openapi.RateLimitError

export type GetACustomFeedSPostsResponse = [[200, GetACustomFeedSPostsResponse200], [401, GetACustomFeedSPostsResponse401], [404, GetACustomFeedSPostsResponse404], [429, GetACustomFeedSPostsResponse429]]

export interface GetACustomFeedSPostsAPI {
  id: "GetACustomFeedSPosts";
  method: "get";
  query: GetACustomFeedSPostsQueryParams;
  pathParams: GetACustomFeedSPostsPathParams;
  requestBody: null;
  response: GetACustomFeedSPostsResponse;
}

export type PatchUpdateCustomFeedSettingsPathParams = {
  feedId: string;
}

export type PatchUpdateCustomFeedSettingsRequestBody = {
  name: string;
  icon: string;
  orderBy: string;
  minDayRange: number;
  minUpvotes: number;
  minViews: number;
  disableEngagementFilter: boolean;
}

export type PatchUpdateCustomFeedSettingsResponse200 = openapi.CustomFeed

export type PatchUpdateCustomFeedSettingsResponse401 = openapi.Error

export type PatchUpdateCustomFeedSettingsResponse404 = openapi.Error

export type PatchUpdateCustomFeedSettingsResponse429 = openapi.RateLimitError

export type PatchUpdateCustomFeedSettingsResponse = [[200, PatchUpdateCustomFeedSettingsResponse200], [401, PatchUpdateCustomFeedSettingsResponse401], [404, PatchUpdateCustomFeedSettingsResponse404], [429, PatchUpdateCustomFeedSettingsResponse429]]

export interface PatchUpdateCustomFeedSettingsAPI {
  id: "PatchUpdateCustomFeedSettings";
  method: "patch";
  query: null;
  pathParams: PatchUpdateCustomFeedSettingsPathParams;
  requestBody: PatchUpdateCustomFeedSettingsRequestBody;
  response: PatchUpdateCustomFeedSettingsResponse;
}

export type DeleteACustomFeedPathParams = {
  feedId: string;
}

export type DeleteACustomFeedResponse200 = openapi.SuccessResponse

export type DeleteACustomFeedResponse401 = openapi.Error

export type DeleteACustomFeedResponse404 = openapi.Error

export type DeleteACustomFeedResponse429 = openapi.RateLimitError

export type DeleteACustomFeedResponse = [[200, DeleteACustomFeedResponse200], [401, DeleteACustomFeedResponse401], [404, DeleteACustomFeedResponse404], [429, DeleteACustomFeedResponse429]]

export interface DeleteACustomFeedAPI {
  id: "DeleteACustomFeed";
  method: "delete";
  query: null;
  pathParams: DeleteACustomFeedPathParams;
  requestBody: null;
  response: DeleteACustomFeedResponse;
}

export type GetCustomFeedMetadataPathParams = {
  feedId: string;
}

export type GetCustomFeedMetadataResponse200 = openapi.CustomFeed

export type GetCustomFeedMetadataResponse401 = openapi.Error

export type GetCustomFeedMetadataResponse404 = openapi.Error

export type GetCustomFeedMetadataResponse429 = openapi.RateLimitError

export type GetCustomFeedMetadataResponse = [[200, GetCustomFeedMetadataResponse200], [401, GetCustomFeedMetadataResponse401], [404, GetCustomFeedMetadataResponse404], [429, GetCustomFeedMetadataResponse429]]

export interface GetCustomFeedMetadataAPI {
  id: "GetCustomFeedMetadata";
  method: "get";
  query: null;
  pathParams: GetCustomFeedMetadataPathParams;
  requestBody: null;
  response: GetCustomFeedMetadataResponse;
}

export type PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedPathParams = {
  feedId: string;
}

export type PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedRequestBody = {
  settings: Array<{
      id: number;
      enabled: boolean;
    }>;
}

export type PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse200 = {
  data: Array<openapi.FeedAdvancedSettings | null>;
}

export type PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse401 = openapi.Error

export type PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse404 = openapi.Error

export type PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse429 = openapi.RateLimitError

export type PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse = [[200, PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse200], [401, PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse401], [404, PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse404], [429, PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse429]]

export interface PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedAPI {
  id: "PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvanced";
  method: "patch";
  query: null;
  pathParams: PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedPathParams;
  requestBody: PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedRequestBody;
  response: PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse;
}

export type GetGlobalFeedSettingsForYouFeedResponse200 = openapi.FeedSettings

export type GetGlobalFeedSettingsForYouFeedResponse401 = openapi.Error

export type GetGlobalFeedSettingsForYouFeedResponse429 = openapi.RateLimitError

export type GetGlobalFeedSettingsForYouFeedResponse = [[200, GetGlobalFeedSettingsForYouFeedResponse200], [401, GetGlobalFeedSettingsForYouFeedResponse401], [429, GetGlobalFeedSettingsForYouFeedResponse429]]

export interface GetGlobalFeedSettingsForYouFeedAPI {
  id: "GetGlobalFeedSettingsForYouFeed";
  method: "get";
  query: null;
  pathParams: null;
  requestBody: null;
  response: GetGlobalFeedSettingsForYouFeedResponse;
}

export type PostFollowTagsGloballyForYouFeedRequestBody = {
  tags: Array<string>;
}

export type PostFollowTagsGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostFollowTagsGloballyForYouFeedResponse401 = openapi.Error

export type PostFollowTagsGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostFollowTagsGloballyForYouFeedResponse = [[200, PostFollowTagsGloballyForYouFeedResponse200], [401, PostFollowTagsGloballyForYouFeedResponse401], [429, PostFollowTagsGloballyForYouFeedResponse429]]

export interface PostFollowTagsGloballyForYouFeedAPI {
  id: "PostFollowTagsGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostFollowTagsGloballyForYouFeedRequestBody;
  response: PostFollowTagsGloballyForYouFeedResponse;
}

export type PostUnfollowTagsGloballyForYouFeedRequestBody = {
  tags: Array<string>;
}

export type PostUnfollowTagsGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostUnfollowTagsGloballyForYouFeedResponse401 = openapi.Error

export type PostUnfollowTagsGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostUnfollowTagsGloballyForYouFeedResponse = [[200, PostUnfollowTagsGloballyForYouFeedResponse200], [401, PostUnfollowTagsGloballyForYouFeedResponse401], [429, PostUnfollowTagsGloballyForYouFeedResponse429]]

export interface PostUnfollowTagsGloballyForYouFeedAPI {
  id: "PostUnfollowTagsGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostUnfollowTagsGloballyForYouFeedRequestBody;
  response: PostUnfollowTagsGloballyForYouFeedResponse;
}

export type PostBlockTagsGloballyForYouFeedRequestBody = {
  tags: Array<string>;
}

export type PostBlockTagsGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostBlockTagsGloballyForYouFeedResponse401 = openapi.Error

export type PostBlockTagsGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostBlockTagsGloballyForYouFeedResponse = [[200, PostBlockTagsGloballyForYouFeedResponse200], [401, PostBlockTagsGloballyForYouFeedResponse401], [429, PostBlockTagsGloballyForYouFeedResponse429]]

export interface PostBlockTagsGloballyForYouFeedAPI {
  id: "PostBlockTagsGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostBlockTagsGloballyForYouFeedRequestBody;
  response: PostBlockTagsGloballyForYouFeedResponse;
}

export type PostUnblockTagsGloballyForYouFeedRequestBody = {
  tags: Array<string>;
}

export type PostUnblockTagsGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostUnblockTagsGloballyForYouFeedResponse401 = openapi.Error

export type PostUnblockTagsGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostUnblockTagsGloballyForYouFeedResponse = [[200, PostUnblockTagsGloballyForYouFeedResponse200], [401, PostUnblockTagsGloballyForYouFeedResponse401], [429, PostUnblockTagsGloballyForYouFeedResponse429]]

export interface PostUnblockTagsGloballyForYouFeedAPI {
  id: "PostUnblockTagsGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostUnblockTagsGloballyForYouFeedRequestBody;
  response: PostUnblockTagsGloballyForYouFeedResponse;
}

export type PostFollowSourcesGloballyForYouFeedRequestBody = {
  sources: Array<string>;
}

export type PostFollowSourcesGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostFollowSourcesGloballyForYouFeedResponse401 = openapi.Error

export type PostFollowSourcesGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostFollowSourcesGloballyForYouFeedResponse = [[200, PostFollowSourcesGloballyForYouFeedResponse200], [401, PostFollowSourcesGloballyForYouFeedResponse401], [429, PostFollowSourcesGloballyForYouFeedResponse429]]

export interface PostFollowSourcesGloballyForYouFeedAPI {
  id: "PostFollowSourcesGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostFollowSourcesGloballyForYouFeedRequestBody;
  response: PostFollowSourcesGloballyForYouFeedResponse;
}

export type PostUnfollowSourcesGloballyForYouFeedRequestBody = {
  sources: Array<string>;
}

export type PostUnfollowSourcesGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostUnfollowSourcesGloballyForYouFeedResponse401 = openapi.Error

export type PostUnfollowSourcesGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostUnfollowSourcesGloballyForYouFeedResponse = [[200, PostUnfollowSourcesGloballyForYouFeedResponse200], [401, PostUnfollowSourcesGloballyForYouFeedResponse401], [429, PostUnfollowSourcesGloballyForYouFeedResponse429]]

export interface PostUnfollowSourcesGloballyForYouFeedAPI {
  id: "PostUnfollowSourcesGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostUnfollowSourcesGloballyForYouFeedRequestBody;
  response: PostUnfollowSourcesGloballyForYouFeedResponse;
}

export type PostBlockSourcesGloballyForYouFeedRequestBody = {
  sources: Array<string>;
}

export type PostBlockSourcesGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostBlockSourcesGloballyForYouFeedResponse401 = openapi.Error

export type PostBlockSourcesGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostBlockSourcesGloballyForYouFeedResponse = [[200, PostBlockSourcesGloballyForYouFeedResponse200], [401, PostBlockSourcesGloballyForYouFeedResponse401], [429, PostBlockSourcesGloballyForYouFeedResponse429]]

export interface PostBlockSourcesGloballyForYouFeedAPI {
  id: "PostBlockSourcesGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostBlockSourcesGloballyForYouFeedRequestBody;
  response: PostBlockSourcesGloballyForYouFeedResponse;
}

export type PostUnblockSourcesGloballyForYouFeedRequestBody = {
  sources: Array<string>;
}

export type PostUnblockSourcesGloballyForYouFeedResponse200 = openapi.SuccessResponse

export type PostUnblockSourcesGloballyForYouFeedResponse401 = openapi.Error

export type PostUnblockSourcesGloballyForYouFeedResponse429 = openapi.RateLimitError

export type PostUnblockSourcesGloballyForYouFeedResponse = [[200, PostUnblockSourcesGloballyForYouFeedResponse200], [401, PostUnblockSourcesGloballyForYouFeedResponse401], [429, PostUnblockSourcesGloballyForYouFeedResponse429]]

export interface PostUnblockSourcesGloballyForYouFeedAPI {
  id: "PostUnblockSourcesGloballyForYouFeed";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostUnblockSourcesGloballyForYouFeedRequestBody;
  response: PostUnblockSourcesGloballyForYouFeedResponse;
}

export type GetCustomFeedFilterSettingsPathParams = {
  feedId: string;
}

export type GetCustomFeedFilterSettingsResponse200 = openapi.FeedSettings

export type GetCustomFeedFilterSettingsResponse401 = openapi.Error

export type GetCustomFeedFilterSettingsResponse404 = openapi.Error

export type GetCustomFeedFilterSettingsResponse429 = openapi.RateLimitError

export type GetCustomFeedFilterSettingsResponse = [[200, GetCustomFeedFilterSettingsResponse200], [401, GetCustomFeedFilterSettingsResponse401], [404, GetCustomFeedFilterSettingsResponse404], [429, GetCustomFeedFilterSettingsResponse429]]

export interface GetCustomFeedFilterSettingsAPI {
  id: "GetCustomFeedFilterSettings";
  method: "get";
  query: null;
  pathParams: GetCustomFeedFilterSettingsPathParams;
  requestBody: null;
  response: GetCustomFeedFilterSettingsResponse;
}

export type PostFollowTagsForACustomFeedPathParams = {
  feedId: string;
}

export type PostFollowTagsForACustomFeedRequestBody = {
  tags: Array<string>;
}

export type PostFollowTagsForACustomFeedResponse200 = openapi.SuccessResponse

export type PostFollowTagsForACustomFeedResponse401 = openapi.Error

export type PostFollowTagsForACustomFeedResponse404 = openapi.Error

export type PostFollowTagsForACustomFeedResponse429 = openapi.RateLimitError

export type PostFollowTagsForACustomFeedResponse = [[200, PostFollowTagsForACustomFeedResponse200], [401, PostFollowTagsForACustomFeedResponse401], [404, PostFollowTagsForACustomFeedResponse404], [429, PostFollowTagsForACustomFeedResponse429]]

export interface PostFollowTagsForACustomFeedAPI {
  id: "PostFollowTagsForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostFollowTagsForACustomFeedPathParams;
  requestBody: PostFollowTagsForACustomFeedRequestBody;
  response: PostFollowTagsForACustomFeedResponse;
}

export type PostUnfollowTagsForACustomFeedPathParams = {
  feedId: string;
}

export type PostUnfollowTagsForACustomFeedRequestBody = {
  tags: Array<string>;
}

export type PostUnfollowTagsForACustomFeedResponse200 = openapi.SuccessResponse

export type PostUnfollowTagsForACustomFeedResponse401 = openapi.Error

export type PostUnfollowTagsForACustomFeedResponse404 = openapi.Error

export type PostUnfollowTagsForACustomFeedResponse429 = openapi.RateLimitError

export type PostUnfollowTagsForACustomFeedResponse = [[200, PostUnfollowTagsForACustomFeedResponse200], [401, PostUnfollowTagsForACustomFeedResponse401], [404, PostUnfollowTagsForACustomFeedResponse404], [429, PostUnfollowTagsForACustomFeedResponse429]]

export interface PostUnfollowTagsForACustomFeedAPI {
  id: "PostUnfollowTagsForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostUnfollowTagsForACustomFeedPathParams;
  requestBody: PostUnfollowTagsForACustomFeedRequestBody;
  response: PostUnfollowTagsForACustomFeedResponse;
}

export type PostBlockTagsForACustomFeedPathParams = {
  feedId: string;
}

export type PostBlockTagsForACustomFeedRequestBody = {
  tags: Array<string>;
}

export type PostBlockTagsForACustomFeedResponse200 = openapi.SuccessResponse

export type PostBlockTagsForACustomFeedResponse401 = openapi.Error

export type PostBlockTagsForACustomFeedResponse404 = openapi.Error

export type PostBlockTagsForACustomFeedResponse429 = openapi.RateLimitError

export type PostBlockTagsForACustomFeedResponse = [[200, PostBlockTagsForACustomFeedResponse200], [401, PostBlockTagsForACustomFeedResponse401], [404, PostBlockTagsForACustomFeedResponse404], [429, PostBlockTagsForACustomFeedResponse429]]

export interface PostBlockTagsForACustomFeedAPI {
  id: "PostBlockTagsForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostBlockTagsForACustomFeedPathParams;
  requestBody: PostBlockTagsForACustomFeedRequestBody;
  response: PostBlockTagsForACustomFeedResponse;
}

export type PostUnblockTagsForACustomFeedPathParams = {
  feedId: string;
}

export type PostUnblockTagsForACustomFeedRequestBody = {
  tags: Array<string>;
}

export type PostUnblockTagsForACustomFeedResponse200 = openapi.SuccessResponse

export type PostUnblockTagsForACustomFeedResponse401 = openapi.Error

export type PostUnblockTagsForACustomFeedResponse404 = openapi.Error

export type PostUnblockTagsForACustomFeedResponse429 = openapi.RateLimitError

export type PostUnblockTagsForACustomFeedResponse = [[200, PostUnblockTagsForACustomFeedResponse200], [401, PostUnblockTagsForACustomFeedResponse401], [404, PostUnblockTagsForACustomFeedResponse404], [429, PostUnblockTagsForACustomFeedResponse429]]

export interface PostUnblockTagsForACustomFeedAPI {
  id: "PostUnblockTagsForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostUnblockTagsForACustomFeedPathParams;
  requestBody: PostUnblockTagsForACustomFeedRequestBody;
  response: PostUnblockTagsForACustomFeedResponse;
}

export type PostFollowSourcesForACustomFeedPathParams = {
  feedId: string;
}

export type PostFollowSourcesForACustomFeedRequestBody = {
  sources: Array<string>;
}

export type PostFollowSourcesForACustomFeedResponse200 = openapi.SuccessResponse

export type PostFollowSourcesForACustomFeedResponse401 = openapi.Error

export type PostFollowSourcesForACustomFeedResponse404 = openapi.Error

export type PostFollowSourcesForACustomFeedResponse429 = openapi.RateLimitError

export type PostFollowSourcesForACustomFeedResponse = [[200, PostFollowSourcesForACustomFeedResponse200], [401, PostFollowSourcesForACustomFeedResponse401], [404, PostFollowSourcesForACustomFeedResponse404], [429, PostFollowSourcesForACustomFeedResponse429]]

export interface PostFollowSourcesForACustomFeedAPI {
  id: "PostFollowSourcesForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostFollowSourcesForACustomFeedPathParams;
  requestBody: PostFollowSourcesForACustomFeedRequestBody;
  response: PostFollowSourcesForACustomFeedResponse;
}

export type PostUnfollowSourcesForACustomFeedPathParams = {
  feedId: string;
}

export type PostUnfollowSourcesForACustomFeedRequestBody = {
  sources: Array<string>;
}

export type PostUnfollowSourcesForACustomFeedResponse200 = openapi.SuccessResponse

export type PostUnfollowSourcesForACustomFeedResponse401 = openapi.Error

export type PostUnfollowSourcesForACustomFeedResponse404 = openapi.Error

export type PostUnfollowSourcesForACustomFeedResponse429 = openapi.RateLimitError

export type PostUnfollowSourcesForACustomFeedResponse = [[200, PostUnfollowSourcesForACustomFeedResponse200], [401, PostUnfollowSourcesForACustomFeedResponse401], [404, PostUnfollowSourcesForACustomFeedResponse404], [429, PostUnfollowSourcesForACustomFeedResponse429]]

export interface PostUnfollowSourcesForACustomFeedAPI {
  id: "PostUnfollowSourcesForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostUnfollowSourcesForACustomFeedPathParams;
  requestBody: PostUnfollowSourcesForACustomFeedRequestBody;
  response: PostUnfollowSourcesForACustomFeedResponse;
}

export type PostBlockSourcesForACustomFeedPathParams = {
  feedId: string;
}

export type PostBlockSourcesForACustomFeedRequestBody = {
  sources: Array<string>;
}

export type PostBlockSourcesForACustomFeedResponse200 = openapi.SuccessResponse

export type PostBlockSourcesForACustomFeedResponse401 = openapi.Error

export type PostBlockSourcesForACustomFeedResponse404 = openapi.Error

export type PostBlockSourcesForACustomFeedResponse429 = openapi.RateLimitError

export type PostBlockSourcesForACustomFeedResponse = [[200, PostBlockSourcesForACustomFeedResponse200], [401, PostBlockSourcesForACustomFeedResponse401], [404, PostBlockSourcesForACustomFeedResponse404], [429, PostBlockSourcesForACustomFeedResponse429]]

export interface PostBlockSourcesForACustomFeedAPI {
  id: "PostBlockSourcesForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostBlockSourcesForACustomFeedPathParams;
  requestBody: PostBlockSourcesForACustomFeedRequestBody;
  response: PostBlockSourcesForACustomFeedResponse;
}

export type PostUnblockSourcesForACustomFeedPathParams = {
  feedId: string;
}

export type PostUnblockSourcesForACustomFeedRequestBody = {
  sources: Array<string>;
}

export type PostUnblockSourcesForACustomFeedResponse200 = openapi.SuccessResponse

export type PostUnblockSourcesForACustomFeedResponse401 = openapi.Error

export type PostUnblockSourcesForACustomFeedResponse404 = openapi.Error

export type PostUnblockSourcesForACustomFeedResponse429 = openapi.RateLimitError

export type PostUnblockSourcesForACustomFeedResponse = [[200, PostUnblockSourcesForACustomFeedResponse200], [401, PostUnblockSourcesForACustomFeedResponse401], [404, PostUnblockSourcesForACustomFeedResponse404], [429, PostUnblockSourcesForACustomFeedResponse429]]

export interface PostUnblockSourcesForACustomFeedAPI {
  id: "PostUnblockSourcesForACustomFeed";
  method: "post";
  query: null;
  pathParams: PostUnblockSourcesForACustomFeedPathParams;
  requestBody: PostUnblockSourcesForACustomFeedRequestBody;
  response: PostUnblockSourcesForACustomFeedResponse;
}

export type GetUserNotificationsQueryParams = {
  limit: number;
  cursor: string;
}

export type GetUserNotificationsResponse200 = {
  data: Array<openapi.Notification>;
  pagination: openapi.Pagination;
}

export type GetUserNotificationsResponse401 = openapi.Error

export type GetUserNotificationsResponse429 = openapi.RateLimitError

export type GetUserNotificationsResponse = [[200, GetUserNotificationsResponse200], [401, GetUserNotificationsResponse401], [429, GetUserNotificationsResponse429]]

export interface GetUserNotificationsAPI {
  id: "GetUserNotifications";
  method: "get";
  query: GetUserNotificationsQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetUserNotificationsResponse;
}

export type GetUnreadNotificationsCountResponse200 = openapi.UnreadCount

export type GetUnreadNotificationsCountResponse401 = openapi.Error

export type GetUnreadNotificationsCountResponse429 = openapi.RateLimitError

export type GetUnreadNotificationsCountResponse = [[200, GetUnreadNotificationsCountResponse200], [401, GetUnreadNotificationsCountResponse401], [429, GetUnreadNotificationsCountResponse429]]

export interface GetUnreadNotificationsCountAPI {
  id: "GetUnreadNotificationsCount";
  method: "get";
  query: null;
  pathParams: null;
  requestBody: null;
  response: GetUnreadNotificationsCountResponse;
}

export type PostMarkAllNotificationsAsReadResponse200 = openapi.SuccessResponse

export type PostMarkAllNotificationsAsReadResponse401 = openapi.Error

export type PostMarkAllNotificationsAsReadResponse429 = openapi.RateLimitError

export type PostMarkAllNotificationsAsReadResponse = [[200, PostMarkAllNotificationsAsReadResponse200], [401, PostMarkAllNotificationsAsReadResponse401], [429, PostMarkAllNotificationsAsReadResponse429]]

export interface PostMarkAllNotificationsAsReadAPI {
  id: "PostMarkAllNotificationsAsRead";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: null;
  response: PostMarkAllNotificationsAsReadResponse;
}

export type GetCurrentUserSProfileResponse200 = openapi.Profile

export type GetCurrentUserSProfileResponse401 = openapi.Error

export type GetCurrentUserSProfileResponse429 = openapi.RateLimitError

export type GetCurrentUserSProfileResponse = [[200, GetCurrentUserSProfileResponse200], [401, GetCurrentUserSProfileResponse401], [429, GetCurrentUserSProfileResponse429]]

export interface GetCurrentUserSProfileAPI {
  id: "GetCurrentUserSProfile";
  method: "get";
  query: null;
  pathParams: null;
  requestBody: null;
  response: GetCurrentUserSProfileResponse;
}

export type PatchUpdateUserProfileRequestBody = {
  name: string;
  bio: string;
  timezone: string;
  weekStart: number;
  experienceLevel: string;
  socialLinks: Array<{
      url: string;
      platform: string;
    }>;
}

export type PatchUpdateUserProfileResponse200 = openapi.Profile

export type PatchUpdateUserProfileResponse400 = openapi.Error

export type PatchUpdateUserProfileResponse401 = openapi.Error

export type PatchUpdateUserProfileResponse429 = openapi.RateLimitError

export type PatchUpdateUserProfileResponse = [[200, PatchUpdateUserProfileResponse200], [400, PatchUpdateUserProfileResponse400], [401, PatchUpdateUserProfileResponse401], [429, PatchUpdateUserProfileResponse429]]

export interface PatchUpdateUserProfileAPI {
  id: "PatchUpdateUserProfile";
  method: "patch";
  query: null;
  pathParams: null;
  requestBody: PatchUpdateUserProfileRequestBody;
  response: PatchUpdateUserProfileResponse;
}

export type GetSearchForToolsTechnologiesByNameQueryParams = {
  query: string;
}

export type GetSearchForToolsTechnologiesByNameResponse200 = {
  data: Array<openapi.Tool>;
}

export type GetSearchForToolsTechnologiesByNameResponse400 = openapi.Error

export type GetSearchForToolsTechnologiesByNameResponse401 = openapi.Error

export type GetSearchForToolsTechnologiesByNameResponse429 = openapi.RateLimitError

export type GetSearchForToolsTechnologiesByNameResponse = [[200, GetSearchForToolsTechnologiesByNameResponse200], [400, GetSearchForToolsTechnologiesByNameResponse400], [401, GetSearchForToolsTechnologiesByNameResponse401], [429, GetSearchForToolsTechnologiesByNameResponse429]]

export interface GetSearchForToolsTechnologiesByNameAPI {
  id: "GetSearchForToolsTechnologiesByName";
  method: "get";
  query: GetSearchForToolsTechnologiesByNameQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetSearchForToolsTechnologiesByNameResponse;
}

export type GetCurrentUserSTechStackQueryParams = {
  limit: number;
  cursor: string;
}

export type GetCurrentUserSTechStackResponse200 = {
  data: Array<openapi.StackItem>;
  pagination: openapi.Pagination;
}

export type GetCurrentUserSTechStackResponse401 = openapi.Error

export type GetCurrentUserSTechStackResponse429 = openapi.RateLimitError

export type GetCurrentUserSTechStackResponse = [[200, GetCurrentUserSTechStackResponse200], [401, GetCurrentUserSTechStackResponse401], [429, GetCurrentUserSTechStackResponse429]]

export interface GetCurrentUserSTechStackAPI {
  id: "GetCurrentUserSTechStack";
  method: "get";
  query: GetCurrentUserSTechStackQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetCurrentUserSTechStackResponse;
}

export type PostAddAToolToUserStackRequestBody = {
  title: string;
  section: string;
  startedAt: string;
}

export type PostAddAToolToUserStackResponse200 = openapi.StackItem

export type PostAddAToolToUserStackResponse400 = openapi.Error

export type PostAddAToolToUserStackResponse401 = openapi.Error

export type PostAddAToolToUserStackResponse429 = openapi.RateLimitError

export type PostAddAToolToUserStackResponse = [[200, PostAddAToolToUserStackResponse200], [400, PostAddAToolToUserStackResponse400], [401, PostAddAToolToUserStackResponse401], [429, PostAddAToolToUserStackResponse429]]

export interface PostAddAToolToUserStackAPI {
  id: "PostAddAToolToUserStack";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostAddAToolToUserStackRequestBody;
  response: PostAddAToolToUserStackResponse;
}

export type PatchUpdateAStackItemPathParams = {
  id: string;
}

export type PatchUpdateAStackItemRequestBody = {
  section: string;
  icon: string;
  title: string;
  startedAt: string;
}

export type PatchUpdateAStackItemResponse200 = openapi.StackItem

export type PatchUpdateAStackItemResponse400 = openapi.Error

export type PatchUpdateAStackItemResponse401 = openapi.Error

export type PatchUpdateAStackItemResponse404 = openapi.Error

export type PatchUpdateAStackItemResponse429 = openapi.RateLimitError

export type PatchUpdateAStackItemResponse = [[200, PatchUpdateAStackItemResponse200], [400, PatchUpdateAStackItemResponse400], [401, PatchUpdateAStackItemResponse401], [404, PatchUpdateAStackItemResponse404], [429, PatchUpdateAStackItemResponse429]]

export interface PatchUpdateAStackItemAPI {
  id: "PatchUpdateAStackItem";
  method: "patch";
  query: null;
  pathParams: PatchUpdateAStackItemPathParams;
  requestBody: PatchUpdateAStackItemRequestBody;
  response: PatchUpdateAStackItemResponse;
}

export type DeleteRemoveAToolFromUserStackPathParams = {
  id: string;
}

export type DeleteRemoveAToolFromUserStackResponse200 = openapi.SuccessResponse

export type DeleteRemoveAToolFromUserStackResponse401 = openapi.Error

export type DeleteRemoveAToolFromUserStackResponse404 = openapi.Error

export type DeleteRemoveAToolFromUserStackResponse429 = openapi.RateLimitError

export type DeleteRemoveAToolFromUserStackResponse = [[200, DeleteRemoveAToolFromUserStackResponse200], [401, DeleteRemoveAToolFromUserStackResponse401], [404, DeleteRemoveAToolFromUserStackResponse404], [429, DeleteRemoveAToolFromUserStackResponse429]]

export interface DeleteRemoveAToolFromUserStackAPI {
  id: "DeleteRemoveAToolFromUserStack";
  method: "delete";
  query: null;
  pathParams: DeleteRemoveAToolFromUserStackPathParams;
  requestBody: null;
  response: DeleteRemoveAToolFromUserStackResponse;
}

export type PutReorderStackItemsRequestBody = {
  items: Array<{
      id: string;
      position: number;
      section: string;
    }>;
}

export type PutReorderStackItemsResponse200 = {
  data: Array<openapi.StackItem>;
}

export type PutReorderStackItemsResponse400 = openapi.Error

export type PutReorderStackItemsResponse401 = openapi.Error

export type PutReorderStackItemsResponse429 = openapi.RateLimitError

export type PutReorderStackItemsResponse = [[200, PutReorderStackItemsResponse200], [400, PutReorderStackItemsResponse400], [401, PutReorderStackItemsResponse401], [429, PutReorderStackItemsResponse429]]

export interface PutReorderStackItemsAPI {
  id: "PutReorderStackItems";
  method: "put";
  query: null;
  pathParams: null;
  requestBody: PutReorderStackItemsRequestBody;
  response: PutReorderStackItemsResponse;
}

export type GetCurrentUserSExperiencesWorkEducationEtcQueryParams = {
  type: string;
  limit: number;
  cursor: string;
}

export type GetCurrentUserSExperiencesWorkEducationEtcResponse200 = {
  data: Array<openapi.UserExperience>;
  pagination: openapi.Pagination;
}

export type GetCurrentUserSExperiencesWorkEducationEtcResponse401 = openapi.Error

export type GetCurrentUserSExperiencesWorkEducationEtcResponse429 = openapi.RateLimitError

export type GetCurrentUserSExperiencesWorkEducationEtcResponse = [[200, GetCurrentUserSExperiencesWorkEducationEtcResponse200], [401, GetCurrentUserSExperiencesWorkEducationEtcResponse401], [429, GetCurrentUserSExperiencesWorkEducationEtcResponse429]]

export interface GetCurrentUserSExperiencesWorkEducationEtcAPI {
  id: "GetCurrentUserSExperiencesWorkEducationEtc";
  method: "get";
  query: GetCurrentUserSExperiencesWorkEducationEtcQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetCurrentUserSExperiencesWorkEducationEtcResponse;
}

export type PostCreateANewExperienceRequestBody = {
  type: string;
  title: string;
  subtitle: string;
  description: string;
  startedAt: string;
  endedAt: string;
  companyId: string;
  customCompanyName: string;
  url: string;
  grade: string;
  externalReferenceId: string;
  customDomain: string;
  repository: {
    id: string;
    owner: string;
    name: string;
    url: string;
    image: string;
  };
  externalLocationId: string;
  locationType: string;
  employmentType: string;
  skills: Array<string>;
}

export type PostCreateANewExperienceResponse200 = openapi.UserExperience

export type PostCreateANewExperienceResponse400 = openapi.Error

export type PostCreateANewExperienceResponse401 = openapi.Error

export type PostCreateANewExperienceResponse429 = openapi.RateLimitError

export type PostCreateANewExperienceResponse = [[200, PostCreateANewExperienceResponse200], [400, PostCreateANewExperienceResponse400], [401, PostCreateANewExperienceResponse401], [429, PostCreateANewExperienceResponse429]]

export interface PostCreateANewExperienceAPI {
  id: "PostCreateANewExperience";
  method: "post";
  query: null;
  pathParams: null;
  requestBody: PostCreateANewExperienceRequestBody;
  response: PostCreateANewExperienceResponse;
}

export type GetASpecificExperienceByIDPathParams = {
  id: string;
}

export type GetASpecificExperienceByIDResponse200 = openapi.UserExperience

export type GetASpecificExperienceByIDResponse401 = openapi.Error

export type GetASpecificExperienceByIDResponse404 = openapi.Error

export type GetASpecificExperienceByIDResponse429 = openapi.RateLimitError

export type GetASpecificExperienceByIDResponse = [[200, GetASpecificExperienceByIDResponse200], [401, GetASpecificExperienceByIDResponse401], [404, GetASpecificExperienceByIDResponse404], [429, GetASpecificExperienceByIDResponse429]]

export interface GetASpecificExperienceByIDAPI {
  id: "GetASpecificExperienceByID";
  method: "get";
  query: null;
  pathParams: GetASpecificExperienceByIDPathParams;
  requestBody: null;
  response: GetASpecificExperienceByIDResponse;
}

export type PutUpdateAnExistingExperiencePathParams = {
  id: string;
}

export type PutUpdateAnExistingExperienceRequestBody = {
  type: string;
  title: string;
  subtitle: string;
  description: string;
  startedAt: string;
  endedAt: string;
  companyId: string;
  customCompanyName: string;
  url: string;
  grade: string;
  externalReferenceId: string;
  customDomain: string;
  repository: {
    id: string;
    owner: string;
    name: string;
    url: string;
    image: string;
  };
  externalLocationId: string;
  locationType: string;
  employmentType: string;
  skills: Array<string>;
}

export type PutUpdateAnExistingExperienceResponse200 = openapi.UserExperience

export type PutUpdateAnExistingExperienceResponse400 = openapi.Error

export type PutUpdateAnExistingExperienceResponse401 = openapi.Error

export type PutUpdateAnExistingExperienceResponse404 = openapi.Error

export type PutUpdateAnExistingExperienceResponse429 = openapi.RateLimitError

export type PutUpdateAnExistingExperienceResponse = [[200, PutUpdateAnExistingExperienceResponse200], [400, PutUpdateAnExistingExperienceResponse400], [401, PutUpdateAnExistingExperienceResponse401], [404, PutUpdateAnExistingExperienceResponse404], [429, PutUpdateAnExistingExperienceResponse429]]

export interface PutUpdateAnExistingExperienceAPI {
  id: "PutUpdateAnExistingExperience";
  method: "put";
  query: null;
  pathParams: PutUpdateAnExistingExperiencePathParams;
  requestBody: PutUpdateAnExistingExperienceRequestBody;
  response: PutUpdateAnExistingExperienceResponse;
}

export type DeleteAnExperiencePathParams = {
  id: string;
}

export type DeleteAnExperienceResponse200 = openapi.SuccessResponse

export type DeleteAnExperienceResponse401 = openapi.Error

export type DeleteAnExperienceResponse404 = openapi.Error

export type DeleteAnExperienceResponse429 = openapi.RateLimitError

export type DeleteAnExperienceResponse = [[200, DeleteAnExperienceResponse200], [401, DeleteAnExperienceResponse401], [404, DeleteAnExperienceResponse404], [429, DeleteAnExperienceResponse429]]

export interface DeleteAnExperienceAPI {
  id: "DeleteAnExperience";
  method: "delete";
  query: null;
  pathParams: DeleteAnExperiencePathParams;
  requestBody: null;
  response: DeleteAnExperienceResponse;
}

export type GetAllTagsResponse200 = {
  data: Array<openapi.Tag>;
}

export type GetAllTagsResponse401 = openapi.Error

export type GetAllTagsResponse429 = openapi.RateLimitError

export type GetAllTagsResponse = [[200, GetAllTagsResponse200], [401, GetAllTagsResponse401], [429, GetAllTagsResponse429]]

export interface GetAllTagsAPI {
  id: "GetAllTags";
  method: "get";
  query: null;
  pathParams: null;
  requestBody: null;
  response: GetAllTagsResponse;
}

export type GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheQueryParams = {
  q: string;
  limit: number;
  cursor: string;
  time: string;
}

export type GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse200 = {
  data: Array<openapi.FeedPost>;
  pagination: openapi.Pagination;
}

export type GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse400 = openapi.Error

export type GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse401 = openapi.Error

export type GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse429 = openapi.RateLimitError

export type GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse = [[200, GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse200], [400, GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse400], [401, GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse401], [429, GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse429]]

export interface GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheAPI {
  id: "GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenThe";
  method: "get";
  query: GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse;
}

export type GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredQueryParams = {
  q: string;
  limit: number;
  time: string;
}

export type GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse200 = {
  data: Array<openapi.FeedPost>;
}

export type GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse400 = openapi.Error

export type GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse401 = openapi.Error

export type GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse429 = openapi.RateLimitError

export type GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse = [[200, GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse200], [400, GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse400], [401, GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse401], [429, GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse429]]

export interface GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredAPI {
  id: "GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPowered";
  method: "get";
  query: GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredQueryParams;
  pathParams: null;
  requestBody: null;
  response: GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse;
}

const idToUrl: Record<string, string> = {
  "GetPersonalizedForYouFeed": "/feeds/foryou",
  "GetFeedWithTrendingAndPopularPosts": "/feeds/popular",
  "GetFeedOfPostsWithDiscussions": "/feeds/discussed",
  "GetPostsByTag": "/feeds/tag/{tag}",
  "GetPostsBySource": "/feeds/source/{source}",
  "GetPostDetailsByID": "/posts/{id}",
  "GetCommentsForAPost": "/posts/{id}/comments",
  "GetSearchPostsByKeyword": "/search/posts",
  "GetSearchTagsByName": "/search/tags",
  "GetSearchSourcesPublishersByName": "/search/sources",
  "GetUserSBookmarkedPosts": "/bookmarks/",
  "PostAddPostsToBookmarks": "/bookmarks/",
  "GetSearchWithinBookmarks": "/bookmarks/search",
  "GetUserSBookmarkLists": "/bookmarks/lists",
  "PostCreateANewBookmarkList": "/bookmarks/lists",
  "DeleteABookmarkList": "/bookmarks/lists/{id}",
  "DeleteRemoveAPostFromBookmarks": "/bookmarks/{id}",
  "PatchMoveABookmarkToAListOrRemoveFromList": "/bookmarks/{id}",
  "GetAllAvailableAdvancedSettingsThatCanBeConfiguredFor": "/feeds/custom/advanced-settings",
  "PostCreateANewCustomFeed": "/feeds/custom/",
  "GetListUserSCustomFeeds": "/feeds/custom/",
  "GetACustomFeedSPosts": "/feeds/custom/{feedId}",
  "PatchUpdateCustomFeedSettings": "/feeds/custom/{feedId}",
  "DeleteACustomFeed": "/feeds/custom/{feedId}",
  "GetCustomFeedMetadata": "/feeds/custom/{feedId}/info",
  "PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvanced": "/feeds/custom/{feedId}/advanced",
  "GetGlobalFeedSettingsForYouFeed": "/feeds/filters/",
  "PostFollowTagsGloballyForYouFeed": "/feeds/filters/tags/follow",
  "PostUnfollowTagsGloballyForYouFeed": "/feeds/filters/tags/unfollow",
  "PostBlockTagsGloballyForYouFeed": "/feeds/filters/tags/block",
  "PostUnblockTagsGloballyForYouFeed": "/feeds/filters/tags/unblock",
  "PostFollowSourcesGloballyForYouFeed": "/feeds/filters/sources/follow",
  "PostUnfollowSourcesGloballyForYouFeed": "/feeds/filters/sources/unfollow",
  "PostBlockSourcesGloballyForYouFeed": "/feeds/filters/sources/block",
  "PostUnblockSourcesGloballyForYouFeed": "/feeds/filters/sources/unblock",
  "GetCustomFeedFilterSettings": "/feeds/filters/{feedId}",
  "PostFollowTagsForACustomFeed": "/feeds/filters/{feedId}/tags/follow",
  "PostUnfollowTagsForACustomFeed": "/feeds/filters/{feedId}/tags/unfollow",
  "PostBlockTagsForACustomFeed": "/feeds/filters/{feedId}/tags/block",
  "PostUnblockTagsForACustomFeed": "/feeds/filters/{feedId}/tags/unblock",
  "PostFollowSourcesForACustomFeed": "/feeds/filters/{feedId}/sources/follow",
  "PostUnfollowSourcesForACustomFeed": "/feeds/filters/{feedId}/sources/unfollow",
  "PostBlockSourcesForACustomFeed": "/feeds/filters/{feedId}/sources/block",
  "PostUnblockSourcesForACustomFeed": "/feeds/filters/{feedId}/sources/unblock",
  "GetUserNotifications": "/notifications/",
  "GetUnreadNotificationsCount": "/notifications/unread/count",
  "PostMarkAllNotificationsAsRead": "/notifications/read",
  "GetCurrentUserSProfile": "/profile/",
  "PatchUpdateUserProfile": "/profile/",
  "GetSearchForToolsTechnologiesByName": "/profile/stack/search",
  "GetCurrentUserSTechStack": "/profile/stack/",
  "PostAddAToolToUserStack": "/profile/stack/",
  "PatchUpdateAStackItem": "/profile/stack/{id}",
  "DeleteRemoveAToolFromUserStack": "/profile/stack/{id}",
  "PutReorderStackItems": "/profile/stack/reorder",
  "GetCurrentUserSExperiencesWorkEducationEtc": "/profile/experiences/",
  "PostCreateANewExperience": "/profile/experiences/",
  "GetASpecificExperienceByID": "/profile/experiences/{id}",
  "PutUpdateAnExistingExperience": "/profile/experiences/{id}",
  "DeleteAnExperience": "/profile/experiences/{id}",
  "GetAllTags": "/tags/",
  "GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenThe": "/recommend/keyword",
  "GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPowered": "/recommend/semantic",
}
export function createDailyDevRequestInit(id: "GetPersonalizedForYouFeed", method: "get", data: {
  searchParams: GetPersonalizedForYouFeedQueryParams;
})
: RequestInit & { url: string, id: "GetPersonalizedForYouFeed" };
export function createDailyDevRequestInit(id: "GetFeedWithTrendingAndPopularPosts", method: "get", data: {
  searchParams: GetFeedWithTrendingAndPopularPostsQueryParams;
})
: RequestInit & { url: string, id: "GetFeedWithTrendingAndPopularPosts" };
export function createDailyDevRequestInit(id: "GetFeedOfPostsWithDiscussions", method: "get", data: {
  searchParams: GetFeedOfPostsWithDiscussionsQueryParams;
})
: RequestInit & { url: string, id: "GetFeedOfPostsWithDiscussions" };
export function createDailyDevRequestInit(id: "GetPostsByTag", method: "get", data: {
  searchParams: GetPostsByTagQueryParams;
  pathParams: GetPostsByTagPathParams;
})
: RequestInit & { url: string, id: "GetPostsByTag" };
export function createDailyDevRequestInit(id: "GetPostsBySource", method: "get", data: {
  searchParams: GetPostsBySourceQueryParams;
  pathParams: GetPostsBySourcePathParams;
})
: RequestInit & { url: string, id: "GetPostsBySource" };
export function createDailyDevRequestInit(id: "GetPostDetailsByID", method: "get", data: {
  pathParams: GetPostDetailsByIDPathParams;
})
: RequestInit & { url: string, id: "GetPostDetailsByID" };
export function createDailyDevRequestInit(id: "GetCommentsForAPost", method: "get", data: {
  searchParams: GetCommentsForAPostQueryParams;
  pathParams: GetCommentsForAPostPathParams;
})
: RequestInit & { url: string, id: "GetCommentsForAPost" };
export function createDailyDevRequestInit(id: "GetSearchPostsByKeyword", method: "get", data: {
  searchParams: GetSearchPostsByKeywordQueryParams;
})
: RequestInit & { url: string, id: "GetSearchPostsByKeyword" };
export function createDailyDevRequestInit(id: "GetSearchTagsByName", method: "get", data: {
  searchParams: GetSearchTagsByNameQueryParams;
})
: RequestInit & { url: string, id: "GetSearchTagsByName" };
export function createDailyDevRequestInit(id: "GetSearchSourcesPublishersByName", method: "get", data: {
  searchParams: GetSearchSourcesPublishersByNameQueryParams;
})
: RequestInit & { url: string, id: "GetSearchSourcesPublishersByName" };
export function createDailyDevRequestInit(id: "GetUserSBookmarkedPosts", method: "get", data: {
  searchParams: GetUserSBookmarkedPostsQueryParams;
})
: RequestInit & { url: string, id: "GetUserSBookmarkedPosts" };
export function createDailyDevRequestInit(id: "PostAddPostsToBookmarks", method: "post", data: {
  body: PostAddPostsToBookmarksRequestBody;
})
: RequestInit & { url: string, id: "PostAddPostsToBookmarks" };
export function createDailyDevRequestInit(id: "GetSearchWithinBookmarks", method: "get", data: {
  searchParams: GetSearchWithinBookmarksQueryParams;
})
: RequestInit & { url: string, id: "GetSearchWithinBookmarks" };
export function createDailyDevRequestInit(id: "GetUserSBookmarkLists", method: "get")
: RequestInit & { url: string, id: "GetUserSBookmarkLists" };
export function createDailyDevRequestInit(id: "PostCreateANewBookmarkList", method: "post", data: {
  body: PostCreateANewBookmarkListRequestBody;
})
: RequestInit & { url: string, id: "PostCreateANewBookmarkList" };
export function createDailyDevRequestInit(id: "DeleteABookmarkList", method: "delete", data: {
  pathParams: DeleteABookmarkListPathParams;
})
: RequestInit & { url: string, id: "DeleteABookmarkList" };
export function createDailyDevRequestInit(id: "DeleteRemoveAPostFromBookmarks", method: "delete", data: {
  pathParams: DeleteRemoveAPostFromBookmarksPathParams;
})
: RequestInit & { url: string, id: "DeleteRemoveAPostFromBookmarks" };
export function createDailyDevRequestInit(id: "PatchMoveABookmarkToAListOrRemoveFromList", method: "patch", data: {
  pathParams: PatchMoveABookmarkToAListOrRemoveFromListPathParams;
  body: PatchMoveABookmarkToAListOrRemoveFromListRequestBody;
})
: RequestInit & { url: string, id: "PatchMoveABookmarkToAListOrRemoveFromList" };
export function createDailyDevRequestInit(id: "GetAllAvailableAdvancedSettingsThatCanBeConfiguredFor", method: "get")
: RequestInit & { url: string, id: "GetAllAvailableAdvancedSettingsThatCanBeConfiguredFor" };
export function createDailyDevRequestInit(id: "PostCreateANewCustomFeed", method: "post", data: {
  body: PostCreateANewCustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostCreateANewCustomFeed" };
export function createDailyDevRequestInit(id: "GetListUserSCustomFeeds", method: "get", data: {
  searchParams: GetListUserSCustomFeedsQueryParams;
})
: RequestInit & { url: string, id: "GetListUserSCustomFeeds" };
export function createDailyDevRequestInit(id: "GetACustomFeedSPosts", method: "get", data: {
  searchParams: GetACustomFeedSPostsQueryParams;
  pathParams: GetACustomFeedSPostsPathParams;
})
: RequestInit & { url: string, id: "GetACustomFeedSPosts" };
export function createDailyDevRequestInit(id: "PatchUpdateCustomFeedSettings", method: "patch", data: {
  pathParams: PatchUpdateCustomFeedSettingsPathParams;
  body: PatchUpdateCustomFeedSettingsRequestBody;
})
: RequestInit & { url: string, id: "PatchUpdateCustomFeedSettings" };
export function createDailyDevRequestInit(id: "DeleteACustomFeed", method: "delete", data: {
  pathParams: DeleteACustomFeedPathParams;
})
: RequestInit & { url: string, id: "DeleteACustomFeed" };
export function createDailyDevRequestInit(id: "GetCustomFeedMetadata", method: "get", data: {
  pathParams: GetCustomFeedMetadataPathParams;
})
: RequestInit & { url: string, id: "GetCustomFeedMetadata" };
export function createDailyDevRequestInit(id: "PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvanced", method: "patch", data: {
  pathParams: PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedPathParams;
  body: PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedRequestBody;
})
: RequestInit & { url: string, id: "PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvanced" };
export function createDailyDevRequestInit(id: "GetGlobalFeedSettingsForYouFeed", method: "get")
: RequestInit & { url: string, id: "GetGlobalFeedSettingsForYouFeed" };
export function createDailyDevRequestInit(id: "PostFollowTagsGloballyForYouFeed", method: "post", data: {
  body: PostFollowTagsGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostFollowTagsGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "PostUnfollowTagsGloballyForYouFeed", method: "post", data: {
  body: PostUnfollowTagsGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnfollowTagsGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "PostBlockTagsGloballyForYouFeed", method: "post", data: {
  body: PostBlockTagsGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostBlockTagsGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "PostUnblockTagsGloballyForYouFeed", method: "post", data: {
  body: PostUnblockTagsGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnblockTagsGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "PostFollowSourcesGloballyForYouFeed", method: "post", data: {
  body: PostFollowSourcesGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostFollowSourcesGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "PostUnfollowSourcesGloballyForYouFeed", method: "post", data: {
  body: PostUnfollowSourcesGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnfollowSourcesGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "PostBlockSourcesGloballyForYouFeed", method: "post", data: {
  body: PostBlockSourcesGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostBlockSourcesGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "PostUnblockSourcesGloballyForYouFeed", method: "post", data: {
  body: PostUnblockSourcesGloballyForYouFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnblockSourcesGloballyForYouFeed" };
export function createDailyDevRequestInit(id: "GetCustomFeedFilterSettings", method: "get", data: {
  pathParams: GetCustomFeedFilterSettingsPathParams;
})
: RequestInit & { url: string, id: "GetCustomFeedFilterSettings" };
export function createDailyDevRequestInit(id: "PostFollowTagsForACustomFeed", method: "post", data: {
  pathParams: PostFollowTagsForACustomFeedPathParams;
  body: PostFollowTagsForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostFollowTagsForACustomFeed" };
export function createDailyDevRequestInit(id: "PostUnfollowTagsForACustomFeed", method: "post", data: {
  pathParams: PostUnfollowTagsForACustomFeedPathParams;
  body: PostUnfollowTagsForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnfollowTagsForACustomFeed" };
export function createDailyDevRequestInit(id: "PostBlockTagsForACustomFeed", method: "post", data: {
  pathParams: PostBlockTagsForACustomFeedPathParams;
  body: PostBlockTagsForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostBlockTagsForACustomFeed" };
export function createDailyDevRequestInit(id: "PostUnblockTagsForACustomFeed", method: "post", data: {
  pathParams: PostUnblockTagsForACustomFeedPathParams;
  body: PostUnblockTagsForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnblockTagsForACustomFeed" };
export function createDailyDevRequestInit(id: "PostFollowSourcesForACustomFeed", method: "post", data: {
  pathParams: PostFollowSourcesForACustomFeedPathParams;
  body: PostFollowSourcesForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostFollowSourcesForACustomFeed" };
export function createDailyDevRequestInit(id: "PostUnfollowSourcesForACustomFeed", method: "post", data: {
  pathParams: PostUnfollowSourcesForACustomFeedPathParams;
  body: PostUnfollowSourcesForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnfollowSourcesForACustomFeed" };
export function createDailyDevRequestInit(id: "PostBlockSourcesForACustomFeed", method: "post", data: {
  pathParams: PostBlockSourcesForACustomFeedPathParams;
  body: PostBlockSourcesForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostBlockSourcesForACustomFeed" };
export function createDailyDevRequestInit(id: "PostUnblockSourcesForACustomFeed", method: "post", data: {
  pathParams: PostUnblockSourcesForACustomFeedPathParams;
  body: PostUnblockSourcesForACustomFeedRequestBody;
})
: RequestInit & { url: string, id: "PostUnblockSourcesForACustomFeed" };
export function createDailyDevRequestInit(id: "GetUserNotifications", method: "get", data: {
  searchParams: GetUserNotificationsQueryParams;
})
: RequestInit & { url: string, id: "GetUserNotifications" };
export function createDailyDevRequestInit(id: "GetUnreadNotificationsCount", method: "get")
: RequestInit & { url: string, id: "GetUnreadNotificationsCount" };
export function createDailyDevRequestInit(id: "PostMarkAllNotificationsAsRead", method: "post")
: RequestInit & { url: string, id: "PostMarkAllNotificationsAsRead" };
export function createDailyDevRequestInit(id: "GetCurrentUserSProfile", method: "get")
: RequestInit & { url: string, id: "GetCurrentUserSProfile" };
export function createDailyDevRequestInit(id: "PatchUpdateUserProfile", method: "patch", data: {
  body: PatchUpdateUserProfileRequestBody;
})
: RequestInit & { url: string, id: "PatchUpdateUserProfile" };
export function createDailyDevRequestInit(id: "GetSearchForToolsTechnologiesByName", method: "get", data: {
  searchParams: GetSearchForToolsTechnologiesByNameQueryParams;
})
: RequestInit & { url: string, id: "GetSearchForToolsTechnologiesByName" };
export function createDailyDevRequestInit(id: "GetCurrentUserSTechStack", method: "get", data: {
  searchParams: GetCurrentUserSTechStackQueryParams;
})
: RequestInit & { url: string, id: "GetCurrentUserSTechStack" };
export function createDailyDevRequestInit(id: "PostAddAToolToUserStack", method: "post", data: {
  body: PostAddAToolToUserStackRequestBody;
})
: RequestInit & { url: string, id: "PostAddAToolToUserStack" };
export function createDailyDevRequestInit(id: "PatchUpdateAStackItem", method: "patch", data: {
  pathParams: PatchUpdateAStackItemPathParams;
  body: PatchUpdateAStackItemRequestBody;
})
: RequestInit & { url: string, id: "PatchUpdateAStackItem" };
export function createDailyDevRequestInit(id: "DeleteRemoveAToolFromUserStack", method: "delete", data: {
  pathParams: DeleteRemoveAToolFromUserStackPathParams;
})
: RequestInit & { url: string, id: "DeleteRemoveAToolFromUserStack" };
export function createDailyDevRequestInit(id: "PutReorderStackItems", method: "put", data: {
  body: PutReorderStackItemsRequestBody;
})
: RequestInit & { url: string, id: "PutReorderStackItems" };
export function createDailyDevRequestInit(id: "GetCurrentUserSExperiencesWorkEducationEtc", method: "get", data: {
  searchParams: GetCurrentUserSExperiencesWorkEducationEtcQueryParams;
})
: RequestInit & { url: string, id: "GetCurrentUserSExperiencesWorkEducationEtc" };
export function createDailyDevRequestInit(id: "PostCreateANewExperience", method: "post", data: {
  body: PostCreateANewExperienceRequestBody;
})
: RequestInit & { url: string, id: "PostCreateANewExperience" };
export function createDailyDevRequestInit(id: "GetASpecificExperienceByID", method: "get", data: {
  pathParams: GetASpecificExperienceByIDPathParams;
})
: RequestInit & { url: string, id: "GetASpecificExperienceByID" };
export function createDailyDevRequestInit(id: "PutUpdateAnExistingExperience", method: "put", data: {
  pathParams: PutUpdateAnExistingExperiencePathParams;
  body: PutUpdateAnExistingExperienceRequestBody;
})
: RequestInit & { url: string, id: "PutUpdateAnExistingExperience" };
export function createDailyDevRequestInit(id: "DeleteAnExperience", method: "delete", data: {
  pathParams: DeleteAnExperiencePathParams;
})
: RequestInit & { url: string, id: "DeleteAnExperience" };
export function createDailyDevRequestInit(id: "GetAllTags", method: "get")
: RequestInit & { url: string, id: "GetAllTags" };
export function createDailyDevRequestInit(id: "GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenThe", method: "get", data: {
  searchParams: GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheQueryParams;
})
: RequestInit & { url: string, id: "GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenThe" };
export function createDailyDevRequestInit(id: "GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPowered", method: "get", data: {
  searchParams: GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredQueryParams;
})
: RequestInit & { url: string, id: "GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPowered" };

export function createDailyDevRequestInit(
  id: string,
  method: string,
  data?: {
    body?: object;
    searchParams?: object;
    pathParams?: object;
  },
): RequestInit & { url: string, id: string } {
  const { baseURL, authToken } = dailyDevConfig;
  const urlStr = new URL(baseURL);
  urlStr.pathname = pathUnix.join(urlStr.pathname, `${idToUrl[id]}`)

  const { body, searchParams, pathParams } = data ?? {};
  if (pathParams) {
    urlStr.pathname = urlStr.pathname.replace(
      /%7B(\w+)%7D/g,
      (_, paramName) => {
        const paramValue = Reflect.get(pathParams, paramName);
        if (!paramValue) {
          throw new Error(`Missing path parameter: ${paramName}`);
        }
        return paramValue;
      },
    );
  }

  if (searchParams) {
    for (const [key, value] of Object.entries(searchParams)) {
      urlStr.searchParams.set(key, `${value}`);
    }
  }

  return {
    id,
    url: urlStr.toString(),
    method,
    headers: {
      ...(body? { "Content-Type": "application/json" } : null),
      "Authorization": `Bearer ${authToken}`,
    },
    ...(body ? { body: JSON.stringify(body) } : null),
  };
}

const dailyDevConfig = {
  baseURL: "",
  authToken: ""
}

export function setDailyDevConfig(baseURL: string, authToken: string) {
  dailyDevConfig.baseURL = baseURL
  dailyDevConfig.authToken = authToken
}



declare global {

  export type FetchMoreResult<Responses extends [number, unknown][]> = {
    [K in Responses[number][0]]: {
      status: K;
      json(): Promise<Extract<Responses[number], [K, unknown]>[1]>;
    };
  }[Responses[number][0]];

  export function fetch(url: string, data: RequestInit & { id: "GetPersonalizedForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetPersonalizedForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetFeedWithTrendingAndPopularPosts" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetFeedWithTrendingAndPopularPostsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetFeedOfPostsWithDiscussions" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetFeedOfPostsWithDiscussionsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetPostsByTag" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetPostsByTagResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetPostsBySource" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetPostsBySourceResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetPostDetailsByID" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetPostDetailsByIDResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetCommentsForAPost" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetCommentsForAPostResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetSearchPostsByKeyword" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetSearchPostsByKeywordResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetSearchTagsByName" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetSearchTagsByNameResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetSearchSourcesPublishersByName" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetSearchSourcesPublishersByNameResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetUserSBookmarkedPosts" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetUserSBookmarkedPostsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostAddPostsToBookmarks" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostAddPostsToBookmarksResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetSearchWithinBookmarks" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetSearchWithinBookmarksResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetUserSBookmarkLists" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetUserSBookmarkListsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostCreateANewBookmarkList" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostCreateANewBookmarkListResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "DeleteABookmarkList" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<DeleteABookmarkListResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "DeleteRemoveAPostFromBookmarks" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<DeleteRemoveAPostFromBookmarksResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PatchMoveABookmarkToAListOrRemoveFromList" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PatchMoveABookmarkToAListOrRemoveFromListResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetAllAvailableAdvancedSettingsThatCanBeConfiguredFor" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetAllAvailableAdvancedSettingsThatCanBeConfiguredForResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostCreateANewCustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostCreateANewCustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetListUserSCustomFeeds" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetListUserSCustomFeedsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetACustomFeedSPosts" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetACustomFeedSPostsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PatchUpdateCustomFeedSettings" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PatchUpdateCustomFeedSettingsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "DeleteACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<DeleteACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetCustomFeedMetadata" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetCustomFeedMetadataResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvanced" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PatchUpdateCustomFeedAdvancedSettingsUseGETFeedsCustomAdvancedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetGlobalFeedSettingsForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetGlobalFeedSettingsForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostFollowTagsGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostFollowTagsGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnfollowTagsGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnfollowTagsGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostBlockTagsGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostBlockTagsGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnblockTagsGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnblockTagsGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostFollowSourcesGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostFollowSourcesGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnfollowSourcesGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnfollowSourcesGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostBlockSourcesGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostBlockSourcesGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnblockSourcesGloballyForYouFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnblockSourcesGloballyForYouFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetCustomFeedFilterSettings" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetCustomFeedFilterSettingsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostFollowTagsForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostFollowTagsForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnfollowTagsForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnfollowTagsForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostBlockTagsForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostBlockTagsForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnblockTagsForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnblockTagsForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostFollowSourcesForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostFollowSourcesForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnfollowSourcesForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnfollowSourcesForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostBlockSourcesForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostBlockSourcesForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostUnblockSourcesForACustomFeed" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostUnblockSourcesForACustomFeedResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetUserNotifications" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetUserNotificationsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetUnreadNotificationsCount" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetUnreadNotificationsCountResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostMarkAllNotificationsAsRead" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostMarkAllNotificationsAsReadResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetCurrentUserSProfile" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetCurrentUserSProfileResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PatchUpdateUserProfile" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PatchUpdateUserProfileResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetSearchForToolsTechnologiesByName" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetSearchForToolsTechnologiesByNameResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetCurrentUserSTechStack" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetCurrentUserSTechStackResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostAddAToolToUserStack" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostAddAToolToUserStackResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PatchUpdateAStackItem" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PatchUpdateAStackItemResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "DeleteRemoveAToolFromUserStack" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<DeleteRemoveAToolFromUserStackResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PutReorderStackItems" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PutReorderStackItemsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetCurrentUserSExperiencesWorkEducationEtc" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetCurrentUserSExperiencesWorkEducationEtcResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PostCreateANewExperience" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PostCreateANewExperienceResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetASpecificExperienceByID" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetASpecificExperienceByIDResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "PutUpdateAnExistingExperience" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<PutUpdateAnExistingExperienceResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "DeleteAnExperience" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<DeleteAnExperienceResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetAllTags" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetAllTagsResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenThe" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetEXPERIMENTALRecommendArticlesByKeywordSearchBestWhenTheResponse>>;
  export function fetch(url: string, data: RequestInit & { id: "GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPowered" }, typed: true): PromiseLike<Omit<Response, "status" | "json"> & FetchMoreResult<GetEXPERIMENTALRecommendArticlesBySemanticSearchUsesAIPoweredResponse>>;
}
