/** This file is auto-generated by build-openapi-client.mts. Do not edit directly. */
export interface Source {
  id: string;
  name: string;
  handle: string;
  image: string | null;
}

export interface CustomFeedFlags {
  name: string | null;
  icon: string | null;
  orderBy: string | null;
  minDayRange: number | null;
  minUpvotes: number | null;
  minViews: number | null;
  disableEngagementFilter: boolean | null;
}

export interface CustomFeed {
  id: string;
  userId: string | null;
  slug: string | null;
  createdAt: string | null;
  flags: CustomFeedFlags;
}

export interface FeedAdvancedSettings {
  id: number;
  enabled: boolean;
}

export interface FeedSettings {
  id: string | null;
  userId: string | null;
  includeTags: Array<string>;
  blockedTags: Array<string>;
  includeSources: Array<Source>;
  excludeSources: Array<Source>;
  advancedSettings: Array<FeedAdvancedSettings>;
}

export interface NotificationAvatar {
  referenceId: string;
  type: string;
  image: string | null;
  name: string;
  targetUrl: string;
}

export interface NotificationAttachment {
  type: string;
  image: string | null;
  title: string;
}

export interface Notification {
  id: string;
  createdAt: string;
  readAt: string | null;
  icon: string;
  title: string;
  type: string;
  description: string | null;
  referenceId: string;
  targetUrl: string;
  numTotalAvatars: number | null;
  avatars: Array<NotificationAvatar>;
  attachments: Array<NotificationAttachment>;
}

export interface UnreadCount {
  count: number;
}

export interface SocialLink {
  platform: string;
  url: string;
}

export interface UserLocation {
  city: string | null;
  country: string | null;
}

export interface Profile {
  id: string;
  name: string | null;
  username: string | null;
  bio: string | null;
  readme: string | null;
  readmeHtml: string | null;
  image: string | null;
  cover: string | null;
  createdAt: string;
  reputation: number;
  permalink: string;
  isPlus: boolean | null;
  experienceLevel: string | null;
  socialLinks: Array<SocialLink>;
  location: UserLocation;
}

export interface Tool {
  id: string;
  title: string;
  faviconUrl: string | null;
}

export interface StackItem {
  id: string;
  section: string;
  position: number;
  startedAt: string | null;
  icon: string | null;
  title: string | null;
  createdAt: string;
  tool: Tool;
}

export interface SuccessResponse {
  success: boolean;
}

export interface Author {
  name: string;
  image: string | null;
}

export interface AuthorWithId {
  id: string;
  name: string;
  image: string | null;
  username: string | null;
}

export interface FeedPost {
  id: string;
  title: string;
  url: string;
  image: string | null;
  summary: string | null;
  type: string;
  publishedAt: string | null;
  createdAt: string;
  commentsPermalink: string;
  source: Source;
  tags: Array<string>;
  readTime: number | null;
  numUpvotes: number;
  numComments: number;
  author: Author;
}

export interface PostDetail {
  id: string;
  title: string;
  url: string | null;
  image: string | null;
  summary: string | null;
  type: string;
  publishedAt: string | null;
  createdAt: string;
  commentsPermalink: string;
  source: Source;
  author: AuthorWithId;
  tags: Array<string>;
  readTime: number | null;
  numUpvotes: number;
  numComments: number;
  bookmarked: boolean;
  content: string | null;
  userState: {
    vote: number;
  };
}

export interface Pagination {
  hasNextPage: boolean;
  cursor: string | null;
}

export interface Error {
  error: string;
  message: string;
}

export interface RateLimitError {
  error: string;
  message: string;
  retryAfter: number;
}

export interface Tag {
  name: string;
}

export interface SourceSummary {
  id: string;
  name: string;
  handle: string;
  image: string | null;
  description: string | null;
}

export interface BookmarkList {
  id: string;
  name: string;
  icon: string | null;
  createdAt: string;
}

export interface BookmarkedPost {
  id: string;
  title: string;
  url: string;
  image: string | null;
  summary: string | null;
  type: string;
  publishedAt: string | null;
  createdAt: string;
  commentsPermalink: string;
  source: Source;
  tags: Array<string>;
  readTime: number | null;
  numUpvotes: number;
  numComments: number;
  author: Author;
  bookmarkedAt: string;
}

export interface CommentAuthor {
  id: string;
  name: string;
  username: string | null;
  image: string | null;
  permalink: string;
}

export interface CommentUserState {
  vote: number;
}

export interface Comment {
  id: string;
  content: string;
  contentHtml: string;
  createdAt: string;
  lastUpdatedAt: string | null;
  permalink: string;
  numUpvotes: number;
  numAwards: number;
  author: CommentAuthor;
  userState: CommentUserState;
  children: Array<Comment>;
}

export interface UserExperienceCompany {
  id: string;
  name: string;
  image: string | null;
}

export interface UserExperienceCustomLocation {
  city: string | null;
  subdivision: string | null;
  country: string | null;
}

export interface UserExperienceSkill {
  value: string;
}

export interface UserExperienceRepository {
  id: string | null;
  owner: string | null;
  name: string;
  url: string;
  image: string | null;
}

export interface ProtoEnumValue {
  value: string;
}

export interface UserExperience {
  id: string;
  type: string;
  title: string;
  subtitle: string | null;
  grade: string | null;
  description: string | null;
  createdAt: string;
  startedAt: string | null;
  endedAt: string | null;
  customCompanyName: string | null;
  customDomain: string | null;
  image: string | null;
  employmentType: ProtoEnumValue;
  locationType: ProtoEnumValue;
  verified: boolean | null;
  url: string | null;
  isOwner: boolean | null;
  skills: Array<UserExperienceSkill>;
  company: UserExperienceCompany;
  customLocation: UserExperienceCustomLocation;
  repository: UserExperienceRepository;
}
